

kafka:
  group:
    id: track-count
  client:
    id: track-count
  bootstrap:
    servers: https://processing.envirocar.org:9092

trackcount:
  mapMatching:
    url: https://processing.envirocar.org/